import {
    MicrosoftIcon,
    IntercomIcon,
    ShopifyIcon,
    GoogleIcon,
    WixIcon,
    DisneyIcon,
    PayPalIcon,
    ChimpMailIcon,
    EvernoteIcon,
    InvisionIcons
  } from '../assets/Icons';

//Dumy datalist

export const initialRows = [
    {
      id: 1,
      product: "Microsoft",
      img: <MicrosoftIcon/>,
      customer: "Implement an AI driven program",
      members: "1 March",
      category: "Publishing",
      tag: "#B2Bmarketing",
      status: "30 mins",
    },
    {
      id: 2,
      product: "Shopify",
      img: <ShopifyIcon/>,
      customer: "Introduce a cloud-based platform",
      members: "1 March",
      category: "E-commerce",
      tag: "#OnlineShopping",
      status: "Tomorrow",
    },
    {
      id: 3,
      product: "MailChimp",
      img: <ChimpMailIcon/>,  
      customer: "Develop mobile app",
      members: "1 March",
      category: "Mobile",
      tag: "#Cloud",
      status: "No contact",
    },
    {
      id: 4,
      product: "PayPal",
      img: <PayPalIcon/>,
      customer: "This program could include",
      members: "1 March",
      category: "Marketplace",
      tag: "#BuySellOnline",
      status: "Next month",
    },
    {
      id: 5,
      product: "Disney",
      img: <DisneyIcon/>,
      customer: "Introduce B2B solution",
      members: "1 March",
      category: "B2B",
      tag: "#BuissnessPartnership",
      status: "1 hour",
    },
    {
      id: 6,
      product: "Intercom",
      img: <IntercomIcon />,
      customer: "Implement an AI driven program",
      members: "1 March",
      category: "SAAS",
      tag: "#SmartFinance",
      status: "Tomorrow",
    },
    {
      id: 7,
      product: "Google",
      img: <GoogleIcon/>,
      customer: "Offer a comprehensive app",
      members: "1 March",
      category: "Finance",
      tag: "#SmartFinance",
      status: "Next month",
    },
    {
      id: 8,
      product: "Everncote",
      img: <EvernoteIcon/>,
      customer: "Implement an AI driven program",
      members: "1 March",
      category: "Transpotation",
      tag: "#LogisticTech",
      status: "No contact",
    },
    {
      id: 9,
      product: "Wix",
      img: <WixIcon/>,
      customer: "Develop a personalized fit",
      members: "1 March",
      category: "Automation",
      tag: "#BuyOnline",
      status: "30 mins",
    },
    {
      id: 10,
      product: "Invision",
      img: <InvisionIcons/>,
      customer: "Implement an AI driven program",
      members: "1 March",
      category: "Web_Services",
      tag: "#APIIntegration",
      status: "Next month",
    },
];
  